### ISSUE TITLE
Compose options for configuration of antivirus scanner and thresholds

### ISSUE THREAD

**Issue by ross-spencer** [artefactual-labs/am#20]
First-cut of a feature file is described here:

artefactual-labs/archivematica-acceptance-tests@3ad5253

Will require merging into RDSS work, likely superseding JiscRDSS#38

Out of scope: Run-time configuration within the AM dashboard/FPR

#### Specific Compose requirements:

* Environment variable placeholders, e.g `CLAMAV_MAXSCANSIZE`, `CLAMAV_MAXFILESIZE`,` CLAMAV_MAXSTREAMSIZE`
* MCPClient AV selection variable, `CLAMAV_BACKEND`

related to: https://github.com/artefactual/archivematica/issues/819

**Comment by sevein** [comment]
@ross-spencer I've merged #25 but I realized there may be a problem:

https://github.com/artefactual-labs/am/blob/ad629aafe688bfe9d91043dc690bc46e13b35898/compose/docker-compose.yml#L143-L147

I think that `ARCHIVEMATICA_MCPCLIENT_CLAMAV_CLIENT_BACKEND` should be renamed to `ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_CLIENT_BACKEND` because it belongs to the `MCPClient` section in the `CONFIG_MAPPING`:

    {'section': 'MCPClient', 'option': 'clamav_client_backend', 'type': 'string'}

Once this is addressed I should also merge #25 into `master`. Let's keep this issue open so I remember!

**Comment by ross-spencer** [comment]
@sevein Not sure what you mean here/what the process is to be. Is this just a style change? Should I make the change in a new pull request?

**Comment by sevein** [comment]
The latter, looks like you've already figured! Thanks. I'll keep this open until I can update the master branch.

**Comment by ross-spencer** [comment]
@sevein if you find time I'd appreciate you taking a look at it and testing with both versions because my testing between scanners with the previous config seemed to be okay. This might only be important if you expect/need the behaviour to be more rigid.

**Comment by ross-spencer** [comment]
Closed by [#26](https://github.com/artefactual-labs/am/pull/26)
