### ISSUE TITLE
Problem: service discovery issues between SS -> Dashboard

### ISSUE THREAD

**Issue by ross-spencer** [artefactual-labs/am#33]
Referenced here: JiscRDSS/rdss-archivematica#103

@mamedin and I confirmed one of the issues experienced locating transfer data is related to this.

**Comment by sevein** [comment]
The Storage Service has a database table where it keeps track of multiple possible Archivematica pipelines. A pipeline is: Dashboard + MCPServer + MCPClient. Some institutions set up multiple pipelines. This model is not necessarily going to be continued forever but it's the way it works today.

The user is requested to register the pipeline in the Storage Service when it is first installed via packages or the Ansible role. It looks like this:

![image](https://user-images.githubusercontent.com/606459/34113123-840c1114-e3c3-11e7-9d45-d86c9a1fa64a.png)
---

When the user submits the form, the corresponding Django view validates the inputs and uses `storageService.create_pipeline` to ask SS to register the pipeline for us.

```python
def create_pipeline(create_default_locations=False, shared_path=None, api_username=None, api_key=None):
    pipeline = {
        'uuid': get_setting('dashboard_uuid'),
        'description': "Archivematica on {}".format(platform.node()),
        'create_default_locations': create_default_locations,
        'shared_path': shared_path,
        'api_username': api_username,
        'api_key': api_key,
    }
    LOGGER.info("Creating pipeline in storage service with %s", pipeline)
    url = _storage_service_url() + 'pipeline/'
    try:
        response = _storage_api_session().post(url, json=pipeline)
        response.raise_for_status()
    except requests.exceptions.RequestException as e:
        LOGGER.warning('Unable to create Archivematica pipeline in storage service from %s because %s', pipeline, e, exc_info=True)
        raise
    return True
```

Storage Service adds the corresponding tuple to its Pipeline table. One field particularly important is `remote_name` which is the way that Storage Service knows how to contact back the pipeline when needed (e.g. during re-ingest of a package).

Storage Service populates the `remote_name` field after the value found in the `REMOTE_ADDR` header. This has worked for us for a long time because the IP address of the Dashboard never changed. Frequently, all the components were set up within the same host or set up manually using static IP addresses. But in setups like Compose or Kubernetes the IP address are constantly changing (e.g. `docker-compose up -d --force-recreate archivematica-dashboard` will cause the container to get a new IP) or you may have more than one replica and each one using a different IP address.

In this kind of situations you need service discovery and within the many patterns available the simplest would be to use DNS, e.g. populate `remote_name` with `http://archivematica-dashboard:8000` would solve the problem because the Docker daemon knows exactly which containers are available and the `A` record for `archivematica-dashboard` reflects that state continuously.

We made a recent change in SS so when we register a pipeline we can also suggest a `remote_name` instead of letting SS guess it which as explained above is not reliable. That happened here: https://github.com/artefactual/archivematica-storage-service/commit/134e33b108d1304f68794de51389f94e4c34ddd1.

In the installer we could update the form so the user can introduce the URL of the Dashboard manually, e.g. see the following mockup:

![image](https://user-images.githubusercontent.com/606459/34113705-6afdf352-e3c5-11e7-96b1-207a9f71be38.png)

In Compose we register the pipeline from the `Makefile` (target `bootstrap-dashboard-db`). We would need to update it so an extra `--remote-url=http://archivematica-dashboard:8000` flag is added.

```shell
	$ docker-compose run \
		--rm \
		--entrypoint /src/dashboard/src/manage.py \
			archivematica-dashboard \
				install \
					--username="test" \
					--password="test" \
					--email="test@test.com" \
					--org-name="test" \
					--org-id="test" \
					--api-key="test" \
					--ss-url="http://archivematica-storage-service:8000" \
					--ss-user="test" \
					--remote-url="http://archvematica-dashboard:8000"
```

---

I'm hoping the problems you've found can be solved with the changes suggested. This would also improve some issues we've had in JiscRDSS where we also use containers. This is even affecting the Jisc core team so I suspect this changeset would be very welcome.

**Comment by sevein** [comment]
This is fixed now, see `--site-url` being used in the `Makefile`.
Also related: https://github.com/artefactual/archivematica-storage-service/pull/267.
